### PR TITLE
Add SHELL statement

### PR DESCRIPTION
**Pull request by bgamari**
Just as it says on the tin.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
recheck ci was not enabled

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
Thank you for the contribution, could you please update the README file too.

**Comment by bgamari** [comment]
@TristanCacqueray done.

**Review by TristanCacqueray — APPROVED** [review]

**Comment by TristanCacqueray** [comment]
@bgamari Great thanks!

**Pull request merged**
